bind r source-file ~/.config/tmux/tmux.conf

# use zsh by default
set-option -g default-shell /bin/zsh

# ctrl+b -> ctrl+a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# altgr dependent defaults
unbind %
unbind '"'
unbind [
unbind ]

# pane navi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# splits
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

# copy mode
setw -g mode-keys vi
bind Escape copy-mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel
bind -T copy-mode-vi Escape send -X cancel

# paste with p
bind p paste-buffer

# window navi
bind -r C-h previous-window
bind -r C-l next-window

# faster escape
set -sg escape-time 0

# enable mouse
set -g mouse on

# panes (style)
set -g pane-border-style "fg=darkgray"
set -g pane-active-border-style "fg=#002b57"

# statusbar (style)
set -g status-position bottom
set -g status-justify left
set -g status-style "bg=#002b57,fg=white"
set -g status-left " "
set -g status-left-length 10
set -g status-right "%Y-%m-%d %H:%M "
set -g status-right-length 50
setw -g window-status-current-format "#I #W #F"

