#!/usr/bin/env bash

# rsync convenience wrapper

IGNORES="--exclude='.git' --exclude='.gitignore' --exclude='.stormdrain' --exclude='node_modules' --exclude='target'"

usage() {
    echo "usage: up2remote <local> [more locals ..] <remote> (remote format: <user>@<host>:<path>)"
}

[[ "$#" -lt 2 ]] && usage && exit 1
[[ "$1" == "-h" ]] && usage && exit 0

REMOTE="${@: -1}"
SOURCES=("${@:1:$#-1}")

rsync -avz --relative --ignore-missing-args $IGNORES ${SOURCES[@]} $REMOTE

